# Multi layer Neural Networks

In [25]:
import torch
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))


In [27]:
def sigmoid(x):
    return 1/(1+torch.exp(-x))

Exercise: Calculate the output for this multi-layer network using the weights W1 & W2, and the biases, B1 & B2.

In [19]:
print("Features:",features,"\nno. of input units:",n_input, "\nno. of hidden units:",
      n_hidden,"\nno. of output units:",n_output, "\nWeights for inputs to hidden layer:\n", W1,
     "\nWeights for hidden layer to output layer:\n",W2)

Features: tensor([[-0.1468,  0.7861,  0.9468]]) 
no. of input units: 3 
no. of hidden units: 2 
no. of output units: 1 
Weights for inputs to hidden layer:
 tensor([[-1.1143,  1.6908],
        [-0.8948, -0.3556],
        [ 1.2324,  0.1382]]) 
Weights for hidden layer to output layer:
 tensor([[-1.6822],
        [ 0.3177]])


In [28]:
features.size()

torch.Size([1, 3])

In [23]:
W1.size()

torch.Size([3, 2])

In [24]:
W2.size()

torch.Size([2, 1])

In [29]:
out1 = sigmoid(torch.mm(features,W1) + B1)

In [30]:
print(out1)

tensor([[0.6813, 0.4355]])


In [31]:
out1.size()

torch.Size([1, 2])

In [32]:
out2 = sigmoid(torch.mm(out1,W2) + B2)

In [33]:
print(out2)

tensor([[0.3171]])
