In [2]:
#importing PyTorch

import torch as pt

In [8]:
def sigmoid(x):
    return 1/(1+torch.exp(-x)) #values between 0 and 1 

In [38]:
torch.manual_seed(5)  # setting up a seed so the things are predictible
#seeding generates the same value everytime the code is run
features = torch.randn([1,5])

In [39]:
weights = torch.rand_like(features)

In [40]:
bias = torch.randn([1,1])

In [41]:
output = sigmoid(torch.sum(weights * features) + bias)

In [42]:
print(output)

tensor([[0.7864]])


In [44]:
#another way using tensors function sum()

In [46]:
y = sigmoid((features*weights).sum() + bias)

In [47]:
print(y)

tensor([[0.7864]])


# By using matrix Multiplication

for matrix multiplication we need to check the size of the matrices

In [48]:
weights.size()

torch.Size([1, 5])

In [49]:
features.size()

torch.Size([1, 5])

the matrice is [1,5] * [1,5] which is not possible to multiply that is needed to be changed to [1,5] * [5,1]

In [58]:
features.resize_(5,1) #resize_ will change the size of oriinal tensor

tensor([[-0.4868],
        [-0.6038],
        [-0.5581],
        [ 0.6675],
        [-0.1974]])

In [67]:
outmm = sigmoid((torch.mm(weights,features)) + bias) 
# now don.t need to sum as matmul also sum the output

In [65]:
print(outmm)

tensor([[0.7864]])
